name: Test PRs

on:
  pull_request:
    branches: [ main, stable ]
  workflow_dispatch:

jobs:

  testjob1:
    name: run always
    runs-on: ubuntu-latest
    steps:
      - name: dump github object
        run: |
          ! read -r -d '' msg << EOF
          payload ${{ toJson(github) }}
          EOF
          echo "$msg"

  testjob2:
      name: run only for main target
      if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
      runs-on: ubuntu-latest
      steps:
        - name: just echo
          run: echo "Hello main"

  testjob3:
      name: run only for stable target
      if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'stable'
      runs-on: ubuntu-latest
      steps:
        - name: just echo
          run: echo "Hello stable"
