name: Test PRs

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  testjob0:
    name: Check version bumped
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get current version
        id: current_version
        run: |
          out="$(cat ./version)"
          echo "$out"
          echo "::set-output name=current_version::$out"
        shell: bash
      - name: Get latest tag
        id: version_latest
        run: |
          out="$(git describe --abbrev=0 --tags | cut -d'v' -f 2)"
          echo "$out"
          echo "::set-output name=version_latest::$out"
        shell: bash
      - name: fail unless bumped
        if: steps.version_latest.outputs.version_latest == steps.current_version.outputs.current_version
        run: exit 1

  testjob2:
      name: run only for main target
      if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
      runs-on: ubuntu-latest
      steps:
        - name: just echo
          run: echo "Hello main"

  testjob3:
      name: run only for stable target
      if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'stable'
      runs-on: ubuntu-latest
      steps:
        - name: just echo
          run: echo "Hello stable"
