name: release

on:
  release:
    types: [published]
  workflow_dispatch:


env:
  BIN_NAME: testme


jobs:

  checks:
    name: verify release
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.current_version.outputs.current_version }}
      release_info: ${{ steps.release_info.outputs.release_info }}
      asset_bin_url: ${{ steps.release_info.outputs.asset_bin_url }}
      asset_ubuntu_tgz_url: ${{ steps.release_info.outputs.asset_ubuntu_tgz_url }}
      upload_url:  ${{ steps.release_info.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v2

      - name: Get current version
        id: current_version
        run: |
          git fetch --all --tags

          tag="$(git describe --tags --exact-match)"
          echo "$tag"
          version="$(echo "$tag" | sed "s/^v//")"
          echo "$version"

          echo "::set-output name=current_version::$version"
        shell: bash

      - name: Get release info
        id: release_info
        run: |
          release_info="$(curl -s https://api.github.com/repos/${{ github.repository }}/releases \
              | jq '.[] | select(.tag_name == "v${{ steps.current_version.outputs.current_version }}")')"
          echo "::set-output name=release_info::$release_info"
          echo "$release_info"

          asset_bin_url="$(echo "$release_info" \
              | jq -r '.assets[] | select(.name | match("^${{ env.BIN_NAME }}$")) | .browser_download_url')"
          echo "::set-output name=asset_bin_url::$asset_bin_url"
          echo "$asset_bin_url"

          asset_ubuntu_tgz_url="$(echo "$release_info" \
              | jq -r '.assets[] | select(.name | match("^${{ env.BIN_NAME }}.ubuntu.tar.gz$")) | .browser_download_url')"
          echo "::set-output name=asset_ubuntu_tgz_url::$asset_ubuntu_tgz_url"
          echo "$asset_ubuntu_tgz_url"

          asset_macos_tgz_url="$(echo "$release_info" \
              | jq -r '.assets[] | select(.name | match("^${{ env.BIN_NAME }}.macos.tar.gz$")) | .browser_download_url')"
          echo "::set-output name=asset_macos_tgz_url::$asset_macos_tgz_url"
          echo "$asset_macos_tgz_url"

          upload_url="$(echo "$release_info" | jq -r '.upload_url')"
          echo "::set-output name=upload_url::$upload_url"
          echo "$upload_url"
        shell: bash

      - name: check release published
        if: ${{ !steps.release_info.outputs.release_info }}
        run: exit 1


  release:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11 ]
        include:
          - os: ubuntu-20.04
            asset_bin_needed: ${{ !needs.checks.outputs.asset_bin_url }}
            asset_tgz_needed: ${{ !needs.checks.outputs.asset_ubuntu_tgz_url }}
            asset_tgz_name_suffix: .ubuntu.tar.gz
          - os: macos-11
            asset_bin_needed: false
            asset_tgz_needed: ${{ !needs.checks.outputs.asset_macos_tgz_url }}
            asset_tgz_name_suffix: .macos.tar.gz
    if: matrix.asset_bin_needed || matrix.asset_tgz_needed
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: build binary
        run: |
          go build -mod=readonly -o build/${{ env.BIN_NAME }} ./cmd/main.go
          tar czf build/${{ env.BIN_NAME }}${{ matrix.asset_tgz_name_suffix }} -C build ${{ env.BIN_NAME }}
        shell: bash

      - name: upload to GitHub (${{ matrix.os }}, binary)
        if: matrix.asset_bin_needed
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.checks.outputs.upload_url }}
          asset_path: build/${{ env.BIN_NAME }}
          asset_name: ${{ env.BIN_NAME }}
          asset_content_type: application/octet-stream  # TODO check for less generic type

      - name: upload to GitHub (${{ matrix.os }}, archived binary)
        if: matrix.asset_tgz_needed
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.checks.outputs.upload_url }}
          asset_path: build/${{ env.BIN_NAME }}${{ matrix.asset_tgz_name_suffix }}
          asset_name: ${{ env.BIN_NAME }}${{ matrix.asset_tgz_name_suffix }}
          asset_content_type: application/x-gtar
