name: verify

on: [ pull_request ]

env:
  PKG_NAME: didcomm


jobs:

  check-version-bumped:
    name: Check is ready for release
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'stable'
    steps:
      - uses: actions/checkout@v2

      - name: Get current version
        id: current_version
        run: |
          version="$(gradle -q version)"
          echo "$version"
          echo "::set-output name=current_version::$version"
        shell: bash

      # TODO improve (DRY): copy-paste from release.yml
      - name: Get release info
        id: release_info
        run: |
          release_info="$(curl -s https://api.github.com/repos/${{ github.repository }}/releases \
              | jq '.[] | select(.name == "v${{ steps.current_version.outputs.current_version }}")')"
          echo "::set-output name=release_info::$release_info"
          echo "$release_info"
        shell: bash

      - name: check version bumped
        # TODO check if greater than latest tag / release (?)
        if: steps.release_info.outputs.release_info
        run: exit 1

      - name: check it can be packaged
        if: false  # TODO
        run: |
          cargo package
          # TODO verify that it's not more than crates.io limit (10 MB)
          ls -la target/package
          cargo package --list
        shell: bash

  test:
    strategy:
      matrix:
        #os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Execute tests
        run: |
          gradle test
